name: PR Synchronize Diff Checker

on:
  pull_request:
    types: [synchronize]

jobs:
  fetch_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all repositories
        run: |
          PAGE=1
          while true; do
            RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.MODULE_GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/orgs/{your-organization}/repos?per_page=100&page=$PAGE")
            if [ "$(echo "$RESPONSE" | jq -r '. | length')" -eq 0 ]; then
              break
            fi
            echo "$RESPONSE" | jq -r '.[].full_name' >> repos.txt
            PAGE=$((PAGE + 1))
          done
          echo "Fetched repositories:"
          cat repos.txt

