name: Fetch Organization Repositories

on:
  workflow_dispatch:

jobs:
  fetch_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all repositories
        run: |
          curl -s -H "Authorization: token ${{ secrets.MODULE_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/{your-organization}/repos?per_page=30" \
               | jq -r '.[].full_name' > repos.txt
          echo "Fetched repositories:"
          cat repos.txt
