name: PR Synchronize Diff Checker

on:
  pull_request:
    types: [synchronize]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 履歴全体をフェッチ

      - name: Get changes between base and head branches
        run: |
          # プルリクエストのベースブランチとヘッドブランチを取得
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}
          
          # リモートベースブランチとヘッドブランチをフェッチ
          git fetch origin $BASE_BRANCH
          git fetch origin $HEAD_BRANCH

          # リモートブランチが正しくフェッチされているか確認
          git branch -r

          # 差分を表示（BASE_BRANCHとHEAD_BRANCHの差分）
          echo "Changes between base branch ($BASE_BRANCH) and head branch ($HEAD_BRANCH):"
          git diff origin/$BASE_BRANCH...origin/$HEAD_BRANCH --stat
