name: Fetch Organization Repositories

on:
  workflow_dispatch:

jobs:
  fetch_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all repositories
        run: |
          curl -s -H "Authorization: token ${{ secrets.MODULE_GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/{your-organization}/repos?per_page=30" \
               | jq -r '.[].full_name' > repos.txt
          echo "Fetched repositories:"
          cat repos.txt

      - name: Checkout repositories
        run: |
          while IFS= read -r repo; do
            echo "Checking out $repo"
            git clone "https://github.com/$repo.git"
            # Optionally, you can use actions/checkout here instead of git clone
            # with a specified repository
            # - name: Checkout $repo
            #   uses: actions/checkout@v4
            #   with:
            #     repository: $repo
          done < repos.txt