name: Upload text file to GCS

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # IDトークンの発行を許可
  contents: read   # リポジトリコンテンツへの読み取り権限

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud using Workload Identity
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Google Cloud SDK
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set pass_credentials_to_gsutil true

    - name: Create a text file
      run: |
        echo "This is a test file" > testfile.txt

    - name: Upload file to GCS
      run: |
        gsutil cp testfile.txt gs://your-bucket-name/
