name: CI test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 過去の全コミットを取得

      - name: Find branch base commit
        id: find-base
        run: |
          # feature/testとmainの共通の祖先コミットを取得
          BASE_COMMIT=$(git merge-base origin/main ${{ github.event.pull_request.head.sha }})
          echo "BASE_COMMIT=${BASE_COMMIT}" >> $GITHUB_ENV

      - name: Find all changed files
        id: files-changed
        run: |
          # BASE_COMMITを基準に差分を取得
          echo '```' > changed_files.txt
          git diff --name-only ${{ env.BASE_COMMIT }} >> changed_files.txt
          echo '```' >> changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Comment on pull request
        run: |
          COMMENT_BODY=$(cat changed_files.txt)
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
