name: connection test

on:
  push:
    branches:
      - main

jobs:
  check-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Check last commit hash
        run: echo ${{ github.event.before }}

      - name: Check latest commit hash
        run: echo ${{ github.sha }}

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: get_changed_files
        run: |
          # 最新の2つのコミットを比較し、変更のあったファイルをリストアップ
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

          # 出力をGitHubの出力に設定
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Use changed files
        run: |
          echo "Files changed in the last commit:"
          echo "${{ steps.get_changed_files.outputs.files }}"




# permissions:
#   id-token: write
#   contents: read

# jobs:
#   connection-test:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4

#     - name: 'Authenticate to Google Cloud'
#       uses: 'google-github-actions/auth@v2'
#       with:
#         workload_identity_provider: 'projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.ID_POOLS_ID }}/providers/${{ secrets.PROVIDER_ID }}'
#         service_account: '${{ secrets.SERVICE_ACCOUNT_MAIL_ADDRESS }}'
#         audience: 'https://github.com/Masato-Nishioka'


#     - name: Create test.txt file1
#       run: echo "This is a test file." > test.txt

#     - name: Upload test.txt to Google Cloud Storage
#       run: gsutil cp test.txt gs://terraform-test-masato-nishioka/test.txt