name: connection test

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  connection-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.ID_POOLS_ID }}/providers/${{ secrets.PROVIDER_ID }}'
        service_account: '${{ secrets.SERVICE_ACCOUNT_MAIL_ADDRESS }}'
        audience: 'https://github.com/Masato-Nishioka'