name: CI test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find all changed files
        id: files-changed
        run: |
          git fetch --prune --unshallow
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.event.pull_request.head.sha }}")
          CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ', ' | sed 's/, $//')
          echo "Changed files: $CHANGED_FILES"
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Comment on pull request
        run: |
          COMMENT_BODY="### Changed Files\n\`\`\`\n$CHANGED_FILES\n\`\`\`"
          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGED_FILES: ${{ env.changed_files }}
